language: python
python:
- "3.6"
- "3.7"
dist: xenial
install:
- pip install poetry
- poetry config settings.virtualenvs.create false
- poetry install
script:
- pylint fs/googledrivefs/
- pylint tests/
