language: python
python:
# - "3.6"
# - "3.7"
- "3.8"
dist: xenial
install:
- pip install fs google-api-python-client google-auth pylint requests-oauthlib pyperclip pytest python-coveralls coverage
script:
- pylint fs/googledrivefs/ tests/
- pytest
after_success:
- coveralls
